### ISSUE TITLE
gpsp seg faults with Grand Theft Auto Advance

### ISSUE THREAD

**Issue by neilmunday** [libretro/gpsp#10]
As the title says, gpsp seg faults with "Grand Theft Auto Advance". Note: I am using Arch Linux on the Raspberry Pi.

I don't know if this is related, but gpsp also complains the "game_config.txt" does not exist in the same directory as the ROM even though it does.

**Comment by twinaphex** [comment]
Yeah it's a known compatibility issue with gpSP. It would need core improvements.

**Comment by neilmunday** [comment]
Ok, thanks for the info.

**Comment by davidgfnet** [comment]
I think the last commit c0d8ffa fixes this, right? Please reopen otherwise!
