### ISSUE TITLE
PS Vita latest nightly 6e9104e crashes in game

### ISSUE THREAD

**Issue by 16mpx** [libretro/gpsp#106]
Hi,

latest nightly built 6e9104e for Vita crashes in game with the attached verbose log.
[retroarch__2021_03_13__13_23_54.log](https://github.com/libretro/gpsp/files/6134700/retroarch__2021_03_13__13_23_54.log)

[INFO] [CORE]: Using content: ux0:/roms/Nintendo - Game Boy Advance/Castlevania - Aria of Sorrow (USA).zip.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Average monitor Hz: 59.830083 Hz. (8.446 % frame time deviation, based on 2048 last samples).
[INFO] === Build =======================================
[INFO] Capabilities:  NEON
[INFO] Built: Mar 12 2021
[INFO] Version: 1.9.0
[INFO] =================================================
[INFO] [Input]: Found input driver: "vita".
[INFO] [Overrides]: No core-specific overrides found at "ux0:/data/retroarch/config/gpSP/gpSP.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "ux0:/data/retroarch/config/gpSP/Nintendo - Game Boy Advance.cfg".
[INFO] [Overrides]: No game-specific overrides found at "ux0:/data/retroarch/config/gpSP/Castlevania - Aria of Sorrow (USA).cfg".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Remaps]: Remap directory: "ux0:/data/retroarch/remaps".
[INFO] [Overrides]: Redirecting save file to "ux0:/data/retroarch/savefiles/Castlevania - Aria of Sorrow (USA).srm".
[INFO] [Overrides]: Redirecting save state to "ux0:/data/retroarch/savestates/Castlevania - Aria of Sorrow (USA).state".
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: GET_VARIABLE gpsp_drc:
	enabled
[INFO] [Environ]: GET_VARIABLE gpsp_frameskip:
	disabled
[INFO] [Environ]: GET_VARIABLE gpsp_frameskip_threshold:
	33
[INFO] [Environ]: GET_VARIABLE gpsp_frameskip_interval:
	1
[INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
[INFO] [Environ]: GET_VARIABLE gpsp_color_correction:
	disabled
[INFO] [Environ]: GET_VARIABLE gpsp_frame_mixing:
	disabled
[INFO] [Environ]: GET_VARIABLE gpsp_save_method:
	gpSP
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "B"
[INFO] 	RetroPad, Port 1, Button "Select" => "Select"
[INFO] 	RetroPad, Port 1, Button "Start" => "Start"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "A"
[INFO] 	RetroPad, Port 1, Button "L" => "L"
[INFO] 	RetroPad, Port 1, Button "R" => "R"
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Environ]: SYSTEM_DIRECTORY: "ux0:/data/retroarch/system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: SET_MEMORY_MAPS.
[INFO]    ndx flags  ptr          offset   start    select   disconn  len      addrspace
[INFO]    001 M1A1Bc 0x817c9758 00008000 03000000 03FF8000 00000000 00008000 
[INFO]    002 M1A1Bc 0x817d9758 00008000 02000000 03FF8000 00000000 00008000 
[INFO]    003 M1A1Bc 0x817d9758 00018000 02008000 03FF8000 00000000 00008000 
[INFO]    004 M1A1Bc 0x817d9758 00028000 02010000 03FF8000 00000000 00008000 
[INFO]    005 M1A1Bc 0x817d9758 00038000 02018000 03FF8000 00000000 00008000 
[INFO]    006 M1A1Bc 0x817d9758 00048000 02020000 03FF8000 00000000 00008000 
[INFO]    007 M1A1Bc 0x817d9758 00058000 02028000 03FF8000 00000000 00008000 
[INFO]    008 M1A1Bc 0x817d9758 00068000 02030000 03FF8000 00000000 00008000 
[INFO]    009 M1A1Bc 0x817d9758 00078000 02038000 03FF8000 00000000 00008000 
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: uma0:/cheats/gpSP/Castlevania - Aria of Sorrow (USA).cht
[INFO] [Audio]: Set audio input rate to: 65769.23 Hz.
[INFO] [Video]: Video @ 720x480
[INFO] vita2d_gfx_init: w: 720  h: 480
[INFO] RARCH_SCALE_BASE: 256 input_scale: 1 = 256
[INFO] Format: SCE_GXM_TEXTURE_FORMAT_R5G6B5
[INFO] [Joypad]: Found joypad driver: "vita".
[INFO] [Font]: Using font rendering backend: bitmap.
[INFO] [Video]: Found display server: null
[INFO] [Display]: Found display driver: "vita2d".
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[INFO] [Playlist]: Loading history file: [ux0:/data/retroarch/content_history.lpl].
[INFO] [Playlist]: Loading history file: [ux0:/data/retroarch/content_music_history.lpl].
[INFO] [Playlist]: Loading favorites file: [ux0:/data/retroarch/content_favorites.lpl].
[INFO] [Playlist]: Written to playlist file: ux0:/data/retroarch/content_history.lpl
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY.
[INFO] Creating texture: 240x160

**Comment by davidgfnet** [comment]
Hey there!
Just to clarify would you mind answering some questions?
 - Does this happen with all games or just some?
 - Which is the last version that works well? (Or: does the previous nightly work well?)

**Comment by 16mpx** [comment]
Hello,

- Happens with all the games I have tried so far, (Castlevania series, Crash Bandicoot etc..)
- Previous nightly has the same problem too. Unfortunately I cannot pinpoint the latest working version but can tell that the version from 22/02/2021 built 300d0c0 is working without such issues.

**Comment by davidgfnet** [comment]
But the games work for a bit or dont even start?
I know its a bit of work, but could you try perhaps the nightly from a week ago or so? Ive been adding things recently and theres a few changes :)

**Comment by 16mpx** [comment]
Hi again,

games start, work for a bit and then crashes. 

I have tried also the nightly from 05/03/2021 built cbcb5df and it crashes too. And no worries, I will be more than happy if I can give back/contribute to the homebrew community a bit :)

**Comment by andbass** [comment]
Just chiming in to say I've also encountered issues with the latest nightly build as well on my Vita, I'll try to get a coredump up soon

**Comment by 16mpx** [comment]
Tested with the latest commit 85ba903 and problem still continues..

**Comment by davidgfnet** [comment]
Yeah we know :) A core dump or any other info could help since I dont have a Vita myself.
Some folks agreed to debug it for me, but they are busy, so it might take a couple days until we get to it.

**Comment by SayianPrinceVegeta** [comment]
Also experiencing crashing using gpsp with newer nightly build. I rolled it back to 1.9 stable and it works again, but sadly I'll be missing out on the other 2 cores for GBA without a nightly version or new update.

**Comment by davidgfnet** [comment]
Im sorry i dont have a Vita. Can someone provide some trace perhaps? Drop by discord and I can help with it. Im totally eager to fix this.

**Comment by SayianPrinceVegeta** [comment]
Can I get a link to the discord. I'd like to help as much as I can
-------- Original message --------From: "David G. F." ***@***.***> Date: 3/27/21  7:39 AM  (GMT-06:00) To: libretro/gpsp ***@***.***> Cc: SayianPrinceVegeta ***@***.***>, Manual ***@***.***> Subject: Re: [libretro/gpsp] PS Vita latest nightly 6e9104e crashes in game (#106) 
Im sorry i dont have a Vita. Can someone provide some trace perhaps? Drop by discord and I can help with it. Im totally eager to fix this.

**Comment by davidgfnet** [comment]
Fran sent a fix for this (he's tested it and works!) in the upstream Retroarch:
https://github.com/libretro/RetroArch/pull/12219

Please check a nightly after it gets merged (ie. in a few days) and report back :)

**Comment by SayianPrinceVegeta** [comment]
Awesome, thanks!

**Comment by davidgfnet** [comment]
So I pushed d83f8fbd and this should fix it. Tested on a device for a while and got no crashes. Feel free to reopen if this is still a thing (you will need to wait a day or two for the nightly build in order to test this).

**Comment by 16mpx** [comment]
Tried latest nightly 52088a4 and seems like issue is solved. Core does not crash the Retroarch application and it stays stable during the game play. And I did not experienced any performance hit by this modification.

So, thank you for your efforts.
