### ISSUE TITLE
Dynarec segfault in ARM

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/gpsp#11]
Dynarec is segfaulting in ARM, there is no much info with gdb. I can run the core only if I compiled without dynarec:

```
HAVE_DYNAREC := 0
CFLAGS += -DARM -DARM_ARCH
```

I'm testing with odroid U3 board, Lubuntu 14.04.

It seems gpsp works in android, what's the magic? Is it using dynarec?

**Comment by joolswills** [comment]
According to users on our issue tracker it worked for them before this change - https://github.com/petrockblog/RetroPie-Setup/pull/652#issuecomment-77763187

**Comment by frthery** [comment]
Hi, yes with dynarec core is working well on raspberry pi 1.

**Comment by joolswills** [comment]
Please can we get this re-enabled - if someone is getting a segfault it would be best to get some debugging information first to locate the problem.

**Comment by sergiobenrocha2** [comment]
It's working for rpi and android, maybe soft/hard ABI issue?

Anyone with rpi2 to test it? Or other board which uses hard float ABI ?

**Comment by sergiobenrocha2** [comment]
@joolswills I just re-enabled it.

**Comment by aliaspider** [comment]
this is either a memory write/execute problem, or this svc call :
https://github.com/libretro/gpsp/blob/master/cpu_threaded.c#L231
isn't supported on your platform.

do other cores with a dynarecs work on those platforms where gpsp fails ? like the mupen core, since it uses pretty much the same function.

**Comment by sergiobenrocha2** [comment]
pcsx_rearmed works in odroid, both c1 and u3.

**Comment by sergiobenrocha2** [comment]
gpsp fails in odroid C1 too, which has other CPU (Amlogic S805, cortex a5).

**Comment by sergiobenrocha2** [comment]
mupen is not working, but it's mali related
