### ISSUE TITLE
Nightly Apr 04/21 GBA crash after 1 minute or more

### ISSUE THREAD

**Issue by DRok17** [libretro/gpsp#121]
Using gpsp core from the nightly build causes crash on 2 GBA games I tried on PS Vita.

Final Fantasy VI
Time ran until crash: 1:04

Mario Kart Super Circuit
Time ran until crash: 1:37

I also tried Pokemon FireRed and that worked just fine.

Crash dumps are linked below with gpsp self.

https://we.tl/t-cbGPasIFNP

![2021-04-06-222406-473118](https://user-images.githubusercontent.com/81541725/113802870-6e9a6e80-9729-11eb-8a7b-364cacc8e504.png)

![2021-04-06-222716-247985](https://user-images.githubusercontent.com/81541725/113802869-6e01d800-9729-11eb-80cd-fe2548bd5713.png)

**Comment by Erken22** [comment]
The same problem in the game golden sun, the game crashes after a few minutes..

**Comment by twinaphex** [comment]
Yeah you'll have to wait until a further status update from @davidgfnet . We don't know yet when this will be fixed.

**Comment by Erken22** [comment]
I tested the latest version of the emulator in golden sun, the game still crashes after 2-5 minutes of playing (

**Comment by Erken22** [comment]
I tested the emulator again, but this time I used the original GBA BIOS and now it seems like Golden Sun does not crash

**Comment by davidgfnet** [comment]
So I pushed d83f8fbd and this should fix it. Tested on a device for a while and got no crashes. Feel free to reopen if this is still a thing (you will need to wait a day or two for the nightly build in order to test this).

**Comment by DRok17** [comment]
Ok thanks!

**Comment by DRok17** [comment]
No crashes for me on latest nightly (Apr 30) . Looks fixed! Thanks!
