### ISSUE TITLE
Wii

### ISSUE THREAD

**Issue by Edu789** [libretro/gpsp#122]
Is it possible to implement gpsp on the Wii Retroarch?

**Comment by askotx** [comment]
Use mGBA, faster, better compatibilty, also this is not an issue or a forum

**Comment by davidgfnet** [comment]
gpsp is pretty much hardwired to be a little endian only emulator. Since Wii and GC are both big endian machines that would mean some non-trivial amount of work.
Is there any reason for you not to use mGBA or another emu? I suppose it should be fast enough to work fullspeed right?
Closing this for now. Feel free to comment!

**Comment by Edu789** [comment]
> gpsp is pretty much hardwired to be a little endian only emulator. Since Wii and GC are both big endian machines that would mean some non-trivial amount of work.
> Is there any reason for you not to use mGBA or another emu? I suppose it should be fast enough to work fullspeed right?
> Closing this for now. Feel free to comment!

The other gba emulators work fine in most games, but the heavier ones have a lot of speed drops like Need for Speed...
i've tested gpsp and it's working fine, in heavier games the speed is better than in other emulators, the only problem is in the audio it doesn't work well, in lighter games the audio works fine.

**Comment by davidgfnet** [comment]
I understand. I thought other emus were fast enough for Wii but I see some games are tricky.
What do you mean "i've tested gpsp"? You mean on WIi?

**Comment by Edu789** [comment]
> I understand. I thought other emus were fast enough for Wii but I see some games are tricky.
> What do you mean "i've tested gpsp"? You mean on WIi?

Yes
