### ISSUE TITLE
Final Fantasy V localized to Russian does not work

### ISSUE THREAD

**Issue by Erken22** [libretro/gpsp#126]
When I launch a version of the game localized by fans into Russian. A black screen appears and the game freezes. But if you run the same rum in gbsp-kai via adrenaline, the game works without problems, apart from poor performance. Could you fix a bug that prevents the translated rom from working in the next update?
#

**Comment by davidgfnet** [comment]
I'd need the ROM to be able to test it. You can reach me via Discord :)

**Comment by bulzipke** [comment]
I had a similar problem, and @davidgfnet  helped me :)

gpSP can normally run a 2 power-of-two size rom file.
```
2,097,152
4,194,304
8,388,608
16,777,216
33,554,432
```
If your rom file size is 9,390,592, then you'll have to set it at 16,777,216.
> truncate -s 16M "romfile.gba"

If your rom file size is 6,392,492?, then you'll have to set it at 8,388,608.
> truncate -s 8M "romfile.gba"

Use the command above, will zero pad the rest of the capacity.
This command available on Linux.

**Comment by davidgfnet** [comment]
Yeah, ROM mirroring is weird and gpsp does not really support non-power-of-two ROM sizes. I'd try to truncate the ROM to the next power of two (just append zeros) and that should do the trick.
Please reopen this if still doesn't work.
This fixed the issue for many korean translated ROMs so I'm assuming it could be the same issue for russian.
