### ISSUE TITLE
3DS: Minish Cap cannot roll

### ISSUE THREAD

**Issue by MarioKartFan** [libretro/gpsp#141]
The R button still works for moving items, lifting pots, accessing options etc. but at some point in the last six months or so it is no longer possible to roll in the game. This issue is also being discussed on gbatemp.net.

**Comment by davidgfnet** [comment]
This was fixed 10 days ago, see [this commit](https://github.com/libretro/gpsp/commit/ac3e75a1079473753c7a713eb913c40c24cfffce)
I tested it and it worked for me after the fix, doesn't it work for you? Make sure you use a version that's recent (ie. not older than a week).
Thanks for the report!

**Comment by MarioKartFan** [comment]
My sincere apologies. I thought I had downloaded the latest nightly but it looks like I downloaded a slightly older build.

**Comment by davidgfnet** [comment]
No worries! Happy that it is fixed for you too
