### ISSUE TITLE
[PS2] No sound after loading a state

### ISSUE THREAD

**Issue by Sin2FX** [libretro/gpsp#146]
Games become muted after you give a load state.

**Comment by Sin2FX** [comment]
This occur in the last nightly build but does not occur in the more recent version 1.9.7

**Comment by davidgfnet** [comment]
Yeah as mentioned in https://github.com/libretro/gpsp/issues/144 it's kind of broken.
I'm working on a permanent fix for this, but it takes some time :) Stay tuned!
