### ISSUE TITLE
[Vita] Golden Sun - The Lost Age crashes at game menu

### ISSUE THREAD

**Issue by edwardz** [libretro/gpsp#147]
This is separate from the Golden Sun - TLA bug that's been reported here: https://github.com/libretro/gpsp/issues/62

Because of the bug above crashing upon the opening cinematics, I tried to start a new game via an emulator on the PC and load the save file into Retroarch (in an attempt to bypass the crashing spot). This seems to cause a different bug where the game simply crashes before you can even load the saved game. I've attaching the save file below:
[Golden Sun - The Lost Age (USA, Europe).sav.zip](https://github.com/libretro/gpsp/files/6941805/Golden.Sun.-.The.Lost.Age.USA.Europe.sav.zip)

Some more potential useful information:
* MD5 for the rom is `8efe8b2aaed97149e897570cd123ff6e  Golden Sun - The Lost Age (USA, Europe).gba`
* The crash doesn't happen with dynarec turned off (:exclamation:)
* Tested with a very recent nightly build of the gpSP core `(ce14e25)`
* Using GBA bios

**Comment by davidgfnet** [comment]
Thanks for the thorough report. I updated the referenced bug (where I fixed the "GBA reset").
Perhaps I also fix this bug? I never encountered this bug myself. I hope it's not a broken save file or something.

**Comment by edwardz** [comment]
Just tested the core from the most recent nightly and my issue is fixed! Your other fix might have also fixed this along with it.

Thank you for all your hard work in maintaining and improving this core! @davidgfnet

**Comment by davidgfnet** [comment]
So you used the Vita nightly for today 16th Aug right? (Was just build a few...minutes ago :P)
Good to hear! Lemme close this bug!

**Comment by edwardz** [comment]
I downloaded it closer to 2AM PST, but the filename was definitely `2021-08-16_RetroArch.vpk`. I also double checked the gpSP core and it was the `1409e04` version. I see where your confusion comes from though.... could it be possible that the timestamps here are in UTC? https://buildbot.libretro.com/nightly/playstation/vita/
