### ISSUE TITLE
Castlevania Circle Of Moon crashes during gampleay

### ISSUE THREAD

**Issue by Sin2FX** [libretro/gpsp#152]
Castlevania Circle Of Moon randomly crashes during gameplay
How to reproduce : Just play the game. Sooner or later it will crash.
Retroarch Version : 1.9.9
Platform : Playstation 2
GpSP Version : 0.91 ( 33f1e25099c64d08723d751c0f8dbf576914d4df )
Video showing the Bug (Crashes in the end) : youtube.com/watch?v=vW3C5EepiCo

**Comment by davidgfnet** [comment]
Let's just use issue #153 for this PS2 issues ok? Thanks!
