### ISSUE TITLE
Metroid Fusion pixellation effect doesn't work

### ISSUE THREAD

**Issue by skyfloogle** [libretro/gpsp#156]
Metroid Fusion uses a pixellation effect of some sort when releasing the X parasites from enemies. It conveniently appears [here in the intro](https://youtu.be/Y9T5m1tjGzA?t=103). This effect isn't replicated in gpsp: the enemy just sits there, with no special effects over it.

**Comment by andymcca** [comment]
Working in the new video renderer (being merged soon!) -
https://youtube.com/shorts/IjfhyE_F7SU?feature=shared

**Comment by DerinQyu** [comment]
> Working in the new video renderer (being merged soon!) - https://youtube.com/shorts/IjfhyE_F7SU?feature=shared

nice, I wonder how big the performance hit from this new renderer will be on low end hardware (like a ps vita)

**Comment by davidgfnet** [comment]
This is now fixed, just merged the new video code.
About performance: it is the same (some games gain some lose, but 0% on average). For games that use mosaic and previously unsupported effects, the perf hit is quite small (within 3% or so). Luckily most games barely use mosaic.
