### ISSUE TITLE
[WiiU] Messed Graphics if Rewind is used.

### ISSUE THREAD

**Issue by Ploggy** [libretro/gpsp#163]
If Rewind is used in game the games Graphics become messed, this only lasts until a screen transition, then the Graphics become normal again.

Before Rewind:
![Legend of Zelda, The - The Minish Cap (USA)-161129-154302](https://user-images.githubusercontent.com/1160255/140699690-f2f45d54-54f5-463f-94c3-aded3849d9c7.png)

After Rewind:
![Legend of Zelda, The - The Minish Cap (USA)-161129-154305](https://user-images.githubusercontent.com/1160255/140699692-d051b273-2fff-40d6-b9e6-d1cbb19f487c.png)

**Comment by davidgfnet** [comment]
Just pushed bc0a3cf2 that should fix this.
Since I almost never test these small things on big endian platforms this breaks every now and then :)
Check out the nightly build tonight and lemme know whether it fixed the issue :)

**Comment by Ploggy** [comment]
Will do.  Thank You very much. :)

**Comment by Ploggy** [comment]
@davidgfnet Awesome!! the fix works fine.. no more bad graphics :)

Thanks again mate :)
