### ISSUE TITLE
Banjo Kazooie Grunty's Revenge - crashes to BIOS just after intro (happens on all versions)

### ISSUE THREAD

**Issue by andymcca** [libretro/gpsp#164]
Thought I'd start working through the 'problem' games here -

https://wiki.maemo.org/GpSP/Game_Compatibility

As per the line for this title, it crashes to the BIOS in gpsp as soon as Banjo comes out of his house just after the short intro.

**Comment by andymcca** [comment]
ALSO -

There is an intro with Banjo and some other characters before the game reaches the title screen - on gpSP this doesn't display at all (black screen) but the music plays and eventually the title screen appears.

Both this and the issue above can be experienced within 20 seconds of a fresh boot of the ROM.

**Comment by davidgfnet** [comment]
Oh yeah, this game must have some weird issues. It's the kind of game that will break easily on a small code change.
Never looked into it very deeply, but does it work better/well in other platforms? (I'm thinking on PC for instance)
Does it work without dynarec? (I know it's slow but if it doesnt work on the interpreter might require more debugging).
Thanks!

**Comment by andymcca** [comment]
Thanks for replying David!

Just tried on my Laptop with RetroArch and latest gpSP.  Exactly the same behaviour!

Yes very slow in Interpreter mode (tried on my ARM7 device), but it does the same thing at the same points i.e. black screen where the intro animations should be, and then a restart to BIOS when Banjo comes out of his house after the intro.

**Comment by Sin2FX** [comment]
Yeap this also happens on PS2 is a old problem in all platforms even the old psp non-libretro versions. Even on a version of gpsp that were ported to PS2 has the same crash in this game.

**Comment by andymcca** [comment]
I remember the Banjo Kazooie games on the N64 were notoriously difficult to get running ok on emulators, especially Banjo Tooie.  Rare would push the machine to the limit and use non-standard microcodes etc. 

Same behaviour on both Dynarec and Interpreter for me.

**Comment by andymcca** [comment]
Found a fix for this issue in another emulator - https://github.com/ITotalJustice/notorious_beeg/issues/44

Unfortunately I am currently struggling to apply it in the gpsp code.  I think I should apply in set_cpu_mode function in cpu.c , but doing an AND 16 on newmode doesn't appear to work.

**Comment by andymcca** [comment]
More discussion and progress on fix in this thread -
_Originally posted by @davidgfnet in https://github.com/libretro/gpsp/issues/178#issuecomment-1374482554_

**Comment by davidgfnet** [comment]
I submitted commit https://github.com/libretro/gpsp/commit/4f3c9a5e588bfbd7e8fdf5a929344f01c64e6dbc and should fix this.

**Comment by andymcca** [comment]
> I submitted commit [4f3c9a5](https://github.com/libretro/gpsp/commit/4f3c9a5e588bfbd7e8fdf5a929344f01c64e6dbc) and should fix this.

That's great David - I actually just managed a not-so-quick-and-dirty fix myself on ARM 32-bit by adding some ORRs to the arm_stub.S file to correctly set bit 4 as previously discussed.  Was just coming to do a PR to find you've uploaded a much more comprehensive fix!  Will build and test on RetroArch in a while.  All the best, thanks again!

**Comment by andymcca** [comment]
Just built the core with this latest commit - can confirm that this is now fixed on my Leapster Explorer (MIYOO equivalent)!
