### ISSUE TITLE
Final Fantasy V (Vita) stuck on logo

### ISSUE THREAD

**Issue by Erken22** [libretro/gpsp#170]
My game freezes on the logo, the version from the Russian translation of rom final fantasy 5 on vita. At the same time, if you run this modified rom on psp via gbspkai, the game does not freeze
Link to rom game
https://drive.google.com/file/d/16I8cM1ywFP6QwEmycWCH4VI6YUNAzF0-/view?usp=sharing

**Comment by andymcca** [comment]
That's interesting, I'll try it here and also on the standalone gpsp

**Comment by andymcca** [comment]
OK - it's been a while, but I can confirm that this ROM launches to a black screen on libretro gpsp, in both Dynarec and Interpreter.  I went back to mid-2021 on my builds and it's the same behaviour.

BUT - it launches ok in gpsp 0.91 standalone.  So I will go back further on the builds to see if I can get to a working commit on the libretro build, which may point to the issue.

**Comment by andymcca** [comment]
OK I've gone all the way back to 2015 on the libretro gpsp builds and this exhibits the same behaviour on my ARM32 device, i.e. black screen on startup. So it appears that this one has always been an issue on the libretro port!

**Comment by andymcca** [comment]
Fixed in Commit 413157dedd92aeda6850e92c73d5b3b4809bcb73  ! 😄
