### ISSUE TITLE
3DS / gpsp: Savestates from ~2 year old core won't load after update to latest stable

### ISSUE THREAD

**Issue by Clydefrosch22** [libretro/gpsp#172]
I just updated my cores and retroarch.cia after about two years to the latest stable 1.10.3
Now my old savestates wont load.
Sram does.
Freshly created savestates work fine.

But not the old ones. And as far as I can tell, it only concerns gpsp.

I see mentions of new stavestate implementation 10 months ago, is that where that happened? 
Any way to get my savestates working again?

I'm gonna try reverting to older versions, but i would prefer if i could update...
Edit: I can load them under 1.9.7

Here's a link with an old save (.state) i can't load on my 3ds and one freshly made that i can (.state1) for zero mission (U) 
https://easyupload.io/45ofno

**Comment by andymcca** [comment]
The new savestate implementation involved changes to many parts of the lr-gpSP codebase, so your only real solution is to play forward from your old savestates to get to an SRAM save and then transfer this across to the latest version.
