### ISSUE TITLE
Legacy of Goku II (and maybe other games) needs different save type?

### ISSUE THREAD

**Issue by tapperp** [libretro/gpsp#173]
Getting a screen saying "This game cannot be played on this hardware" when getting to the world map in Legacy of Goku II (USA).

After some research it seems this game needs to be set to save type eeprom. However, I don't see a way to use or edit a game_config.txt as we could do in stand-alone versions of gpSP. Nor is there an option listed to change save type for individual games within retroarch.

Can we even use game_config.txt with gpSP in retroarch? If so, where to place it? 

Please advise. Thank you

Attached is a sav file before the part referenced. You have to walk/run north-east, get the armor in the chest, then keep going north until you get to the world map. That is when it will give that message.
[DBZLOGII sav.zip](https://github.com/libretro/gpsp/files/9007764/DBZLOGII.sav.zip)
.

**Comment by andymcca** [comment]
The code to load game_config.txt and individual game configs is still present in the lr-gpsp codebase but I'm not sure if it works given it originates from the standalone version.

You could try an individual game cfg file using the old standalone format, placed in the same directory as the ROM (or the Core) - similarly, a game_config.txt file.

The other alternative is to submit a pull request on the gba_over.h file, which is essentially a hard-coded version of game_config.txt (have a look at the repo).  @d30r did a commit in May last year to essentially do the same thing you're talking about - you can view it here: https://github.com/d30r/gpsp/commit/5e71cd14d185e52c78944a0d5ca3bc5aeea877b4

**Comment by andymcca** [comment]
Having another look at this one.  The following entry can be added to gba_over.h to cover this game -

  {
      // Dragon Ball Z: Legacy of Goku II (U)
      "DBZLGCYGOKU2",              /* gamepak_title        */
      "ALFE",                      /* gamepak_code         */
      "70",                        /* gamepak_maker        */
      0,                           /* flash_size           */
      FLASH_DEVICE_UNDEFINED,      /* flash_device_id      */
      2,                           /* save_type            */
      0,                           /* rtc_enabled          */
      0,                          /* idle_loop_target_pc  */
      0,                           /* translation_gate_target_1 */
      0,                           /* translation_gate_target_2 */
      0,                           /* translation_gate_target_3 */
   },

Based on what I've seen, the save_type should be set to 2 to indicate eeprom, but I am guessing as can't see a spec for this file.  I'm also not sure if the libretro codebase (specifically gba_memory.c) still contains code to process this, because as far as I can see, none of the current entries in this file have anything other than a '0' specified for save_type.

I see in the Core Options you can select between Backup Save Method (gpsp or libretro), so I would assume that you select gpsp if you want the above.

@davidgfnet, when you have time, can you provide any insight?  I have tried settings 0, 1 and 2 in save_type and built from latest commit but no change in the behaviour described above.

**Comment by andymcca** [comment]
Save state attached.  Just walk forward to the World Map and then tap the button and you will get the message 'This game cannot be played on this hardware', and it will then return to the start of the game.

[Dragon Ball Z - The Legacy of Goku II (USA).zip](https://github.com/libretro/gpsp/files/11208723/Dragon.Ball.Z.-.The.Legacy.of.Goku.II.USA.zip)

**Comment by andymcca** [comment]
A workaround for you until a 'proper' fix is put in place - 

https://gbatemp.net/threads/log1-2-3-ez-flash-iv.348556/#post-4655532

You need to patch the ROM to disable this message.

**Comment by davidgfnet** [comment]
Yeah most emulators have a workaround for these games (even mgba) so I suspect they do something funny with the EEPROM so they can detect "fake" cartridges and/or clones? I do not think we support these at the moment, I will check out whether we can add these quirks too. Only affect a handful of games fortunately.

**Comment by andymcca** [comment]
Thanks David, I suspect issue #189 is a similar problem.

**Comment by andymcca** [comment]
Not sure when/if this one can be fixed, but in the meantime you can use an IPS patch to get the game working in gpsp -

https://wiki.funkey-project.com/wiki/List_of_games_with_compatibility_issues#Games_that_require_patching

**Comment by andymcca** [comment]
Just done a PR to implement save type overrides.  Need to do more testing on it before it can be merged, but I did test an entry for this game to override to EEPROM and it solved the above issue!

**Comment by davidgfnet** [comment]
This is now (should be!) fixed. Thanks for reporting it!
