### ISSUE TITLE
64 bit support

### ISSUE THREAD

**Issue by ustix** [libretro/gpsp#174]
Dear Exophase!

Are you planning to make a 64bit version of this emulator? I have built the retropie on a dietpi bullseye 64 bit with an fbcp-ili9341 screen and i think your emulator is the best one because the others aren't even able to make fast forward fast (that's how I measure their usefulness), so I would be really excited to have your work ready on my experimental setup!

Thanks in advance!

**Comment by ustix** [comment]
@hizzlekizzle can you help in the topic? I have seen your name somewhere, maybe at RetroPie reddit?

**Comment by ustix** [comment]
I think you are right and I shouldn't have to force raspberry pi zero 2 running 64 bit system with retropie, because it doesn't affect its performance in a good way and I am also getting compatibility issues with emulators when their performance matters, like mgba or vba-next is very bad compared to gpsp, but maybe they are not that bad with a pi4 for example (which i don't have, so can't tell really, but i have a radxa zero which is more powerful, so maybe i will try that.).
Thanks for your detailed answer!

**Comment by andymcca** [comment]
There is an ARM64 Dynarec available for this emulator thanks to the work by @davidgfnet, but the core needs to be built with this enabled.  Check out the relevant files in the ARM folder in the repo for more details.

**Comment by davidgfnet** [comment]
There's 64 bit support. You can build the emulator for any 64 bit platforms. There's dynarec support for arm64, x86-64 and even mips64!
