### ISSUE TITLE
[Reques] Add softpatching support

### ISSUE THREAD

**Issue by askotx** [libretro/gpsp#175]
Like other cores, will this be feasible?

**Comment by hizzlekizzle** [comment]
This core is currently set to "needs_fullpath = true", which means it needs direct access to the file on disk instead of loading it into RAM, where it could be softpatched. This is often a fairly big deal to change, as it means changing how the core emulator accesses all ROM data.

**Comment by askotx** [comment]
Fair enough, thanks for explain it. I'll close this issue then.
