### ISSUE TITLE
Crash with GTA

### ISSUE THREAD

**Issue by schmurtzm** [libretro/gpsp#176]
Hello, when dynamic recompiler is disabled, Grand Theft Auto Advance crashes to game selection menu after the intro cinematic and save file creation. It seems to happens only if you try to skip the cinematic dialog.

**To reproduce :** 

https://user-images.githubusercontent.com/7110113/211163210-f473e322-afa6-41b1-af7a-6c073616de40.mp4

- "Select a slot" screen -> press A 4 times
- "jump start" screen -> press A and B
- dialog cinematic screen -> press A to skip -> it crash most of the time

I can reproduce it on Miyoo Mini (little handheld linux console) and on Windows with up to date RA and gpsp core.

No interesting logs in RA (it closes instantly withtout generating logs) .

Tested with last gPSP commit : 90170e33894ac8e3598a5660da62a18884d795f4 5 jan 2023
(As it is not the default setting for most people maybe it's not so important...)

Thank you !

**Comment by andymcca** [comment]
I can't reproduce this using the most up to date builds of RA and lr-gpSP.  Can you confirm this issue still exists?  Thanks.

**Comment by schmurtzm** [comment]
Hi, thanks for the investigation. 
Yes I'm still able to reproduce but I have just realized that it requires "interframe blending" to crash ;)

**Comment by andymcca** [comment]
Understood!  Would you be able to update your issue title to reflect this please?

**Comment by schmurtzm** [comment]
Yes, edited, finally it seems to happens only when "dynamic compiler" is disabled. As it is not the default setting for most people maybe it's not so important...

**Comment by schmurtzm** [comment]
Video added to description

**Comment by andymcca** [comment]
Just to be clear on this, as of the latest commit 2bbd770, the Dynarec works all the way through to in-game.

Interpreter crashes after the initial dialogue whether you skip it or not.

**Comment by andymcca** [comment]
Great work @davidgfnet , it sounds like this one was difficult!  There seem to be so many puzzles like this in gpsp, all with different reasons!  Look forward to trying your commits as always. :-)

**Comment by davidgfnet** [comment]
I think the last commit c0d8ffa fixes this, right? Please reopen otherwise!
