### ISSUE TITLE
Mario & Luigi - Superstar Saga 	- Crashes when entering a battle

### ISSUE THREAD

**Issue by schmurtzm** [libretro/gpsp#182]
Specifically it's a random crash that can happen at the start of battles during the transition screen occurrence seems to be (very roughly) 1 in 15 or so.

Here an example, the sound is very expressive for the crash :D 

https://user-images.githubusercontent.com/7110113/211166617-b41d2fa5-a587-4657-a9ef-113376ed75fe.mp4
Armv7 + neon , same behavior on x86 (Windows) : 
dynarec OFF -> the star animation never run : game video freezed
dynarec ON -> some random crash on battle start (as in the video)

Tested with last gPSP commit : 90170e33894ac8e3598a5660da62a18884d795f4 5 jan 2023

**Comment by andymcca** [comment]
Is the crash recoverable or do you have to restart the device?  I mean is it like a full hardware crash?  What about if you set audio latency really high (like 128ms or higher)?

**Comment by schmurtzm** [comment]
The crash is recoverable. The core is not crashed because it is possible to access to RA menu and restart the game or load a savestate.
(description updated)

**Comment by andymcca** [comment]
I've been poking around the code a lot today.  I'm definitely no expert but I've been able to replicate this kind of noisy crash with other games when I make changes to the cpu modes.  The latest commits by @davidgfnet have fixed some of the issues but I think there's still problems elsewhere in the code, with how gpsp handles changing the modes - can't help but think that a lot of these issues you've raised are symptomatic of the same thing.

**Comment by davidgfnet** [comment]
Yeah it's random and depends on the frontend you use. This indicates some bigger issue like memory corruption or similar in the code. Likely some out of bounds access or similar. Will take longer to debug this issue, specially since reproducing them is a bit of a pain (ie. some issues go away when under a debugger :P)

**Comment by andymcca** [comment]
Argh - that's another level of frustration (i.e. issues disappearing when debugging).   The DemiKids issue also raised recently was the one I was primarily looking at yesterday.  That one at least is similar to the other recent ones you've fixed i.e. reproducable every time at the same place in the game, likely due to the game doing trying to run a weird/unforeseen assembler instruction.

**Comment by davidgfnet** [comment]
The way I test this it can be tricky to catch some bugs where the game just freezes without crashing. I should try find a workaround (like comparing two or more frames to ensure there's progress in the game).
For compatibility I could produce a video for every ROM I test (in an automated fashion) to allow humans to find errors without having to play them all. (Like https://www.youtube.com/watch?v=MI8__NAFaww and https://www.youtube.com/watch?v=TDGx3jMM6_Q)

**Comment by andymcca** [comment]
Very interesting videos @davidgfnet!  In this case, would it be helpful if @schmurtzm can provide a Save State which will always crash at the same point (if this is possible)?

**Comment by andymcca** [comment]
@schmurtzm quick question on this - when it happens, if you go to the RetroArch menu and switch back to Interpreter mode and then go back to the game, does it carry on as normal?

**Comment by davidgfnet** [comment]
Can you guys test it with 2bbd7705 or later? I suspect this could be caused by the pending IRQ bug I just fixed.
Given it takes a few attempts to trigger, it's worth playing a bit with it. Thanks!

**Comment by andymcca** [comment]
Hi David,  I will try this one also - I'm actually playing through this game at the moment, and haven't encountered the issue yet (1 in every 15 battles is very rare!!  Don't even think I'm on battle 15 yet, haha).  I'll start again with your latest commit to see if I get it, will do a Savestate before every battle to see if we can catch it.  Unless @schmurtzm can provide a Savestate?

**Comment by schmurtzm** [comment]
I'll check this and provide a savestate to tonight 😉
Thank you for the investigation !

**Comment by andymcca** [comment]
@schmurtzm I've been playing this on and off throughout the past couple of days on the latest commit 2bbd770.  I've gone through many battles so far and I'm yet to have a crash.

**Comment by andymcca** [comment]
@schmurtzm @davidgfnet I want to say this one is fixed.  I'm up to about 4 hours gameplay now and not a single crash.

**Comment by davidgfnet** [comment]
I think we can call this one fixed, feel free to reopen.
Didnt validate it but it makes sense the kind of bug this game had with the fix. If the IRQ is not raised, the game can potentially freeze forever (I assume that some other IRQ source are disabled, so it doesnt recover from it).
Thanks!
