### ISSUE TITLE
Is wARM still required on ARM9 chips?

### ISSUE THREAD

**Issue by andymcca** [libretro/gpsp#186]
As per the subject title.  

In the standalone gpsp, notaz says that wARM (https://github.com/notaz/warm) is required for cache control on this very old ARM architecture.  I guess this is primarily for devices with the ARM926EJ-S (PowKiddy / BittBoy / Miyoo / Leapster).

Not sure if this is still required and/or of benefit to lr-gpsp?

**Comment by davidgfnet** [comment]
First time I hear about this :)
We do not use this wARM thing AFAIK.  On linux we use __clear_cache which is translated into a syscall. On other platforms (Vita, 3DS) there's some component/backdoor to use for this.
wARM seems an accelerator for these operations on Linux-ARM platforms. However I do not think there are many such platforms that could benefit from this. wARM requires loading a kernel module (which is tricky) and would require root too.

**Comment by andymcca** [comment]
Got it - no problem!
