### ISSUE TITLE
[ARM32/Interpreter] ATV Thunder Ridge Racers - no in-game input

### ISSUE THREAD

**Issue by andymcca** [libretro/gpsp#195]
Once you get past the menus and into the game itself, you cannot start the race as you seemingly can't move.  You can hear the throttle going up, but no movement and no other racers visible.  This happens on both ARM32 Dynarec and Interpreter.  Save State attached.

I have gone back as far as commit c167749 (December 2014) and this issue is still there!  Makes me wonder if it's somehow a RetroArch issue, or more likely something broken when transitioning from standalone to libretro core.
[ATV - Thunder Ridge Riders (USA).zip](https://github.com/libretro/gpsp/files/11208690/ATV.-.Thunder.Ridge.Riders.USA.zip)

gpsp 0.91 standalone (ARM32) doesn't have this issue!

**Comment by davidgfnet** [comment]
Yeah the input bit was a bit misleading, I suspected some IRQ/Timer issue since the other players do not start either. If it was an input problem it would not happen I suppose.
Glad you found it! Let's close this then, thanks!
