### ISSUE TITLE
[All] Several games hanging at startup

### ISSUE THREAD

**Issue by andymcca** [libretro/gpsp#197]
The following games I have tested hang on the first (or second) logo screen displayed after loading -

Street Racing Syndicate
Smashing Drive
Wolfenstein 3D

This affects builds going back to 2015.  All 3 games go past this point on gpsp 0.91 standalone.

**Comment by andymcca** [comment]
I have a suspicion this could be due to commit 41484cd from wayyy back in 2014.  It removes some code relating to backup saves.  Unfortunately I get compiler errors when trying to build from this commit, so would need to reinstate the missing code manually to test the theory.

**Comment by andymcca** [comment]
@davidgfnet - FOUND IT!  Commit 0bc2a11 rewrote the timer update code as part of getting rid of the macros.  If I restore the macro code as written before this commit, then Smashing Drive goes past the 'Licensed by Nintendo' initial screen and in-game!

I haven't time to test anything else just yet as going out, but this gives us something good to go on!

**Comment by andymcca** [comment]
OK doing a PR now which I believe fixes these and perhaps a number of other games....

**Comment by davidgfnet** [comment]
Thanks for finding this! I missed your last comment, I guess I only get notifications where I'm mentioned or something.
