### ISSUE TITLE
[James Pond - Codename Robocod] Black screen after language selection

### ISSUE THREAD

**Issue by DrUm78** [libretro/gpsp#202]
Hardware: FunKey S device (armv7 32-bit) with 64MB RAM
Software: [PicoArch frontend](https://git.crowdedwood.com/picoarch/)
OS: Custom Linux 4.14.14
Commit: https://github.com/libretro/gpsp/commit/2d28451f6cb74eed09203b4b3a2da3549dd27cc9

A black screen appears after the language selection while the intro music keeps playing. We cannot skip the intro or do anything. Seems like this game never worked as it's the same with a very old gpSP direct port from 2016.

**Comment by andymcca** [comment]
I'll check on gpsp 0.91 standalone from 2013 to verify, also will check gpsp 0.9 on PSP as it could be an ARM Dynarec issue.  What about Interpreter mode, does it do the same on that?

**Comment by DrUm78** [comment]
Yep, same issue with the dynarec disabled.
The old gpSP that also has the bug is: https://github.com/FoxCunning/gpsp

**Comment by andymcca** [comment]
Does the same on gpsp 0.9 and Retroarch gpsp on PSP (MIPS), so it's not an ARM issue.

**Comment by andymcca** [comment]
Found a near-identical issue raised and closed on mgba.  Will use this as the basis for further investigation -

https://github.com/mgba-emu/mgba/issues/539

**Comment by andymcca** [comment]
@DrUm78 @davidgfnet - reading through the mgba issue and subsequent fix commit, this looks like another IRQ timing issue.  The fix on mgba is that all IRQs have a 7-cyle delay and implementing this satisfies the specific timing condition necessary to transition from the language screen to the intro.  

I'm not sure how effective this fix can be when implemented on gpsp, as it is very specific on the cycles.  The other option would be a ROM patch to fix, but I don't think one exists currently.

**Comment by andymcca** [comment]
@DrUm78 I've created an IPS patch for this game to fix the issue.  Please use Lunar IPS or similar to patch your ROM and then confirm that all is ok?

[James Pond - Codename Robocod (USA) (En,Fr,Es,Pt).zip](https://github.com/libretro/gpsp/files/11304556/James.Pond.-.Codename.Robocod.USA.En.Fr.Es.Pt.zip)

**Comment by DrUm78** [comment]
@andymcca It works, nice. 👍
Maybe a dumb question but why not include this patch into gpSP code (with a `if james pond` so that it does not break anything else)? Same question for some patches like the ones for Legacy of Goku I & II.

**Comment by andymcca** [comment]
@DrUm78 great 👍 
No not a dumb question, actually there is such a file in gpsp for game-specific fixes but unfortunately it doesn't contain the parameters I needed for this fix, and same for other patches which are more comprehensive than this one anyway.  

Also, even for RetroArch Softpatching I believe it requires the whole ROM to be loaded into RAM, and on some platforms with low RAM we don't do that.  

So at this stage sticking with patches gives the best flexibility and is the way to go for gpsp I think.  

@davidgfnet are you ok/in agreement to close this issue now?

**Comment by DrUm78** [comment]
Indeed, I thought we could put that in the code or into `game_config.txt`, thanks for the explanation. 👍
