### ISSUE TITLE
[Video] Payback - Bitmap/OBJ layer order issues

### ISSUE THREAD

**Issue by andymcca** [libretro/gpsp#207]
In the game Payback, the language and game menus do not display correctly.  The effect looks like extreme blurring.

Having investigated and reviewed the code, this appears to be a corner case issue with the Bitmap/OBJ layer order code.  

For example, changing the order position of the OBJ layer in line number 3455 in video.c (e.g. from 'priority | 0x04' to 'priority | 0x05') makes the menus display correctly - but this breaks other games!  So there is something more going on here.  Opening an issue to keep track.

**Comment by andymcca** [comment]
Have created PR #208 as a potential fix to be reviewed.

**Comment by davidgfnet** [comment]
This game has some serious performance issue with the CPU dynarec code, but this should be treated in a separate Issue/PR. The GFX issues have been now resolved thanks to the mode4-color effects support that just landed. Closing this!
