### ISSUE TITLE
[ARM32] Pokemon Pinball Ruby & Sapphire - Graphics and Restart issues

### ISSUE THREAD

**Issue by andymcca** [libretro/gpsp#210]
There are two issues with this game -

1) When starting a new game, there is a frame in the middle of the Pinball machine which scrolls through various options until you press fire.  This option scrolling seems twice the size of the frame and rather corrupted.  Would be interested to know if this happens in TempGBA as I have an idea as to what the issue may be.

2) After playing the game for around 5 minutes, then restarting the game via the RetroArch menu, the game will begin again and I get as far as the table before either a) the game will restart the to GBA BIOS screen or b) RetroArch will crash out.  Possibly one of the gpsp caches not being fully cleared on game restart?

Thanks
Andy

**Comment by davidgfnet** [comment]
Thanks for the report. Just now I was thinking I need to run a proper "reset" test, that is, loading a ROM, playing, resetting it and doing it again. The output should be the same, but I suspect some stuff is not properly flushed or cleared, causing these weird things you see. Should be easy to test, lemme do a quick run and find all the missing reset machinery.
Thanks!

**Comment by andymcca** [comment]
Yes can confirm the reset issue appears to be fixed!

The other issue with the graphics is once again OBJ Transparency-related (similar to the Golden Sun black boxes issue).  The visible OBJs either side of the slot when it is spinning are transparent and as such should be hidden by the BG layer, but gpsp displays them due to an bug in the OBJ transparency implementation.

**Comment by davidgfnet** [comment]
the restart was indeed fixed. The gfx issues have been fixed as well, just merged the new video code. Enjoy!
