### ISSUE TITLE
[Interpreter] Steel Empire broken on commit 84c347e

### ISSUE THREAD

**Issue by andymcca** [libretro/gpsp#219]
Steel Empire is currently broken in Dynarecs.  Following commit 84c347edadcba216488a2939a1867168b31498d4 it is now also broken in Interpreter mode.

Both modes now exhibit the same behaviour i.e. when starting the ROM there is a short burst of sound, followed by a black screen.

Previously to this commit, you could start Steel Empire in Interpreter mode and then switch to Dynarec and carry one playing.

Likely to be some kind of timing issue introduced, as this is the area this commit improved specifically for Interpreter.

**Comment by davidgfnet** [comment]
Oh, thanks for the finding. The emulator timings are tricky and some games crash if the timing is not properly emulated (even by a few dozen cycles here and there). In most cases it's the game having a bug, but miraculosly avoiding hitting it in a fatal way.

**Comment by davidgfnet** [comment]
I think you mentiont that the last commit c0d8ffa fixes this, right? Haven't been able to reproduce it myself.
