### ISSUE TITLE
Enabling 128k flash saves for gpsp on a PS Vita in Retroarch

### ISSUE THREAD

**Issue by brak265** [libretro/gpsp#222]
I’ve got a Romhack for Pokémon that I’m trying to use in Retroarch on my hacked vita, but it requires 128k flash saves.  How do I enable this?  I can’t find the right directory for the “game_config.txt” file.  The game does work in mgba, but I’d rather use the gpsp core since gpsp is the only core that emulates the game with no audio stutter/slowdown. I’m sorry if this isn’t the best place for this question, I wasn’t sure where else to turn and figured here would be the best.

**Comment by andymcca** [comment]
game_config.txt is picked up from your specified ROMS directory (at least, it is on my device).  You will need to ensure you make an appropriate entry for the ROM, but the Flash 128k option should be honoured in the current version.  Be aware though that game_config.txt is likely to be disabled in an upcoming commit, as it has essentially been superseded by the in-built override file (gba_over.h).

**Comment by davidgfnet** [comment]
I changed a bit the way this works. Can you retry again? I think all games should be able to use 128KB flash, but I could be wrong. Otherwise let us know which rom it is so we can test it. Thanks!
