### ISSUE TITLE
[Android] Golden Sun black screen when summoning Neptune (and Boreas) 

### ISSUE THREAD

**Issue by Burlz10** [libretro/gpsp#226]
When attempting to summon Neptune or Boreas in battle, the attack cutscene turns to black (audio still playing). After attack cutscene finishes, screen goes back to normal. Used the same save file with mGBA to ensure this was a core specific issue. Worked fine on mGBA. Any help is appreciated since a similar request was recently closed on a similar issue but doesn’t seem to affect this specific problem. Thank you.

![C435F7ED-30BE-4A88-AE24-A8640B276F86](https://github.com/libretro/gpsp/assets/145821419/4995d7ab-03c0-4c7a-a0ab-2cf70a4c70d7)
![1822CAB6-2EFD-448B-A79E-0E4FCF3646B3](https://github.com/libretro/gpsp/assets/145821419/b80bf38e-0082-4717-873c-888bb20d2b4f)
![F9827FB9-9141-437C-A331-F710FAC5BBE9](https://github.com/libretro/gpsp/assets/145821419/ecdc651f-25ac-40dd-bb80-077a95e678ac)
![39D62A0A-4AA1-4C49-9C2F-A05A05C2D285](https://github.com/libretro/gpsp/assets/145821419/3b553784-075f-4a03-99a7-de4d7864b66b)
![EF85CABE-107A-4212-A202-D8FB728E8FD8](https://github.com/libretro/gpsp/assets/145821419/5d9bbf3c-5181-42eb-805a-34e03a12bf30)

**Comment by Burlz10** [comment]
Also let me know if the .sav file is required. I have one prepared for testing in case someone addresses issue. Thanks

**Comment by DerinQyu** [comment]
Isn´t this https://github.com/libretro/gpsp/issues/166#issuecomment-1726285872 what you're asking for?

**Comment by Burlz10** [comment]
Yes this is exactly my issue. I didn’t realize someone had already started a ticket for it. Thanks. I also noticed some background element issues. Specifically the rug on the ship that takes you to Tolbi is in the foreground and covers you and the NPCs. Should this be a new ticket? Thanks

**Comment by andymcca** [comment]
Yeah just to confirm, David has fixed this particular issue (Black Screen) in his Dev branch - few minor features and issues like this getting resolved/tested at the moment, will be merged in due course!

**Comment by Burlz10** [comment]
Fantastic. I’m looking forward to it’s release!

**Comment by davidgfnet** [comment]
Ok merged. This should be now fixed in master. Make sure to grab an update with the fixes.
