### ISSUE TITLE
Is the 128KB flash honored?

### ISSUE THREAD

**Issue by kivutar** [libretro/gpsp#23]
Saving fails in Pokemon games.

In gba_over.h, I do see the FLASH_DEVICE_MACRONIX_128KB for POKEMON FIRE

But in RA's log, I see no reference about it:

```
romtitle     : Pokemon: Fire Red (E/U)
gamepak title: POKEMON FIRE
gamepak code : BPRE
gamepak maker: 01
INPUT gamepak title: POKEMON FIRE
INPUT gamepak code : BPRE
INPUT gamepak maker: 01
found entry in over ini file.
```

This flash rom has something to do with saving?

**Comment by andymcca** [comment]
Tested and no issue with saving/restoring in Pokemon Fire Red.  @davidgfnet please close this issue.

**Comment by davidgfnet** [comment]
It can use the libretro saving routines (but doenst by default).
OK closing it then!
