### ISSUE TITLE
new rumble option not works in pokemon pinball

### ISSUE THREAD

**Issue by Ninoh-FOX** [libretro/gpsp#230]
rumble not work in the game, the option not is selecctionable in the game.

**Comment by andymcca** [comment]
Pokemon Pinball does rumble via Gameboy Player by default, which isn't supported yet.  I believe you have to apply the cartridge rumble patch for this one and a couple of other games to get it to work - 

https://gbatemp.net/threads/gamecube-gba-rumble-games-and-rom-hacked-rumble.589863/

**Comment by Ninoh-FOX** [comment]
I am test the patchs in the roms and the rumble not work...

**Comment by davidgfnet** [comment]
GB Player Rumble will come soon, for now it is not supported. Only support for the so-called GPIO.3 rumble (drill dozer and a few homebrew games). Some patches exist for other games and compatibility hacks for Flash-Carts with rumble support.

**Comment by Ninoh-FOX** [comment]
> GB Player Rumble will come soon, for now it is not supported. Only support for the so-called GPIO.3 rumble (drill dozer and a few homebrew games). Some patches exist for other games and compatibility hacks for Flash-Carts with rumble support.

I am test drill dozer and not work, I don't know if is for the system (miyoo mini) or for the compilation, but in mgba works fine.

**Comment by davidgfnet** [comment]
You can post the rom hashes here and I can add them.
Btw you can "force" runble in the options (in case the rom is not in gba_over).

**Comment by Ninoh-FOX** [comment]
Works great with the last changes (01/2024)
