### ISSUE TITLE
Pokemon Sapphire poison screen shake missing

### ISSUE THREAD

**Issue by jloh** [libretro/gpsp#232]
Apologies if this is the wrong place to raise this issue, I'm still new and not sure where it should go!

I recently switched from mGBA to GPSP in Retroarch on a RG405M running GammaOS. I migrated my save by just renaming the `.srv` to `.sav` just in case its relevant.

Everything is going well and the GPSP lets me put the RG405M into power saving mode and still get 60FPS which is fantastic, I'm super impressed.

One thing that differs from the two cores I've found is that the poison effect that happens when a Pokemon is poisoned outside of combat doesn't display on the screen. The sound effect still happens but the visual one doesn't. I'm talking about the second part of this video (apologies for the YouTube short link!) https://www.youtube.com/shorts/kIrzE3rAKo4

I'm running:

 - gpSP v0.91 `7f07da9`
 - BIOS present
 - Using Shaders
 - Video filter Normal4x

Not sure what other information to provide. I use the same video settings across mGBA and GPSP and the only difference between the two is GPSP provides better performance but the poison effect doesn't work, only difference I've been able to notice.

Let me know what other information I can provide to help debug or if I should report this elsewhere!

Again, thanks for the fantastic emulator!

**Comment by andymcca** [comment]
Hey, I'm a bit out of things at the moment, but just a quick message to say please try a more up-to-date build if you can.

The build version you are using is from June this year, and since then the video renderer was completely rewritten, Mosaic effect was implemented and many other things were fixed (please check commit log and closed issues for full detail)!

**Comment by davidgfnet** [comment]
Hey there!
Yes, as Andy says, this version you are using is quite "old". These effects have been fixed (see #156) in newer versions.

**Comment by jloh** [comment]
Thankyou! I'll work out how to upgrade on GammaOS and get back to you 😄
