### ISSUE TITLE
Encrypted Cheat Support Please

### ISSUE THREAD

**Issue by spaceboydavey** [libretro/gpsp#238]
Referencing Issue #90

Please add support for encrypted cheats eg PAR_V3, passing the string of cheat type to gpsp through retroarch should resolve this. Really annoying bug tho.

**Comment by davidgfnet** [comment]
This is not planned. It is simpler to decrypt the cheats (there's many decrypters out there) and stored them that way.
The only reason they are/were encrypted to being with was some sort of anycopy protection, so not a really good reason to support them, sorry.
