### ISSUE TITLE
Set wireless adapter (untester) break rumble support.

### ISSUE THREAD

**Issue by Ninoh-FOX** [libretro/gpsp#241]
I see that set wireless link adapter to yes break rumble support in gameboy player, I think that this is because is two different machines? (Gamecube with gb player or gba/sp with wireless adapter) 

I see too that the data base file don't has all games list with support to link. Maybe is this because is not finish for now the code for link cable adapter?

Great work with the new features!!

**Comment by dude98** [comment]
you can use the GBA Player with the wireless adapter though... that seems to be something that should probably be patched.
A list of supported games (including test romhacks) would probably be a good thing to add to the github files too.

**Comment by davidgfnet** [comment]
The rumble and RFU both use the serial port, so they are incompatible. Not sure how the GBA player could have allowed both RFU and rumble support at the same time.
I do not think this will be fixed/implemented, since there are almost no games that use both (RFU and GBA player rumble). Sorry!
