### ISSUE TITLE
Remap problem with Retroarch.

### ISSUE THREAD

**Issue by Erimatai** [libretro/gpsp#25]
I have configured the buttons A & B to y & b in the Retropad respectively, but I noticed when I press the Y button (B in the gpSP libretro core) it seems to be pressing the L button too. Also I can't configure the remap for GBA L & R buttons in the control core options. Sorry for my bad english and thanks.

**Comment by fr500** [comment]
Someone added extra buttons in yx... I warned against it and that's what's
causing this

**Comment by bmaupin** [comment]
I'm not sure, but it looks like this is the commit that caused this issue: https://github.com/libretro/gpsp/commit/d5075185eff7e680839755b1528a413cac7bbfd4

If that's the case, then it looks like it's been resolved: https://github.com/libretro/gpsp/commit/38007a82f211a33d8521ebaf481666e0bc151a06

My guess is this issue can be closed.

**Comment by davidgfnet** [comment]
This was indeed fixed, thanks for the precise pointers @bmaupin Appreciated!
