### ISSUE TITLE
could you add .u1 extension? (MAME roms set compatibility)

### ISSUE THREAD

**Issue by legluondunet** [libretro/gpsp#37]
Hello,
could you add .u1 extension to the gpsp Libretro module?
I'm using the Gameboy Advance Mame roms set and some of the zipped files contain .u1 extension.
Thank you for your help.

PS: http://forum.pleasuredome.org.uk/index.php?showtopic=30865&hl=

**Comment by andymcca** [comment]
@davidgfnet did a PR for this one (#218) for you to review - can close this issue if you agree and merge.
