### ISSUE TITLE
Android build broken

### ISSUE THREAD

**Issue by fr500** [libretro/gpsp#39]
<retrobot> gpsp-armeabi: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/27366
<retrobot> gpsp-armeabi-v7a: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/27367
<retrobot> gpsp-x86: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/27369

Same issue as picodrive / pcsx

**Comment by davidgfnet** [comment]
This is indeed a dupe of #41 
Also note that due to gcc -> clang move from Google, recent NDKs cannot build gpsp (due to the fact that gpsp uses nested functions which are not supported in clang). I will try to improve this and make the code more portable to hopefully run on newer NDKs.
