### ISSUE TITLE
Auto-load state broken on some games?

### ISSUE THREAD

**Issue by bslenul** [libretro/gpsp#52]
Hey!

Got a really weird bug with some games using the auto-load state option from RetroArch, for example with Mother 3 (tried with both JPN and translated rom), if I quit and start the game again it freezes and make some terrible noises.

However if I manually load the auto-save state it works fine! Ingame saves and normal save states work perfectly fine also.

It doesnt seem to affect every game, no problem with Zelda Minish Cap for example. But its also buggy on Metroid Zero Mission.

Latest RetroArch and gpSP nightlies, heres a video of the bug in Metroid Zero Mission: https://youtu.be/yHVSK0BFvgI

Video made using the following steps:
* I enable auto save and load state.
* I load Metroid, let it play for a few seconds then close content to create the auto save state.
* I load it again and get the freeze + sound looping because of the auto-load state.
* I close content and disable auto save and load state.
* I load Metroid again but this time I manually load the auto save state and it's working fine!

I'm not too sure if its a gpSP or RetroArch bug :/ I post here because I only encountered it with this core so far.

**Comment by bslenul** [comment]
OK looks like the problem is the loading part, not the saving because if I rename the .state.auto file into .state I can manually load the save state with no problem: https://youtu.be/JmaO4EbNj78

Still not sure if its a RA bug or a gpSP one :p And nothing helpful in the log files.

**Comment by fr500** [comment]
Woot

That makes even less sense lol...
The core is unaware of the state filename

**Comment by bslenul** [comment]
Yeah this is super confusing :D

Auto-load state must be doing something slightly different than a manual load state I guess?

I compared the logs between auto-loading state from Mother 3 (not working) and Zelda Minish Cap (working) and the logs are identical (except for paths and filenames of course), even the size of the save state is the same (524288 bytes).

Forgot to mention I encountered the bug on Windows 10 but also on the S/NES Mini (we use auto-save/load state feature a lot on this system).

**Comment by nl255** [comment]
This issue also happens with suspend saves on the NES/SNES Mini systems.

**Comment by mokrates** [comment]
I have the same Issue with lakka on the GPi-Retroflag-Case.

**Comment by bslenul** [comment]
Completely forgot about this issue... It's still happening to this day unfortunately, I tried to bisect but looks like it was already happening back in 2014.

A quick recap of the issue if anyone is interested in looking at it:

* It doesn't happen with every game (Mother 3 and Metroid Zero Mission are affected, Zelda Minish Cap is not).
* The auto-save state created when closing content seems perfectly fine, if you start the game without auto-load state and manually load -1 slot it loads without any issue.
* However if you have auto-load state enabled then you'll get a freeze with terrible sound distortions.

A workaround if you use auto-load state is to use `Quick Menu > Restart` when the bug happens, then load the state in slot "-1".

**Comment by davidgfnet** [comment]
Is this only happening to gpsp or other emulators as well? If it's not gpsp specific perhaps you can have more luck checking the Retroarch issue tracker.

**Comment by bslenul** [comment]
Hey! It only affects gpSP core as far as I can tell.
