### ISSUE TITLE
gp2x WIZ

### ISSUE THREAD

**Issue by markusmo** [libretro/gpsp#53]
Hi guys
I recently reactivated my gp2x WIZ and found your repository after some serious googleing.

The question I have: is it still possible to compile your development to gp2x WIZ ...? I could not find any information about that.

**Comment by andymcca** [comment]
Hi,
As far as I can see, RetroArch didn't get ported to the GP2x devices (although in theory, it could be), so this fork of gpsp won't work on the Wiz unfortunately. @davidgfnet please can you close this issue?
Thanks
Andy
