### ISSUE TITLE
Unable to save game on VITA games

### ISSUE THREAD

**Issue by herrmartell** [libretro/gpsp#59]
On Golden Sun I'm getting "unable to detect backup memory".

Seems to be related to the save type, and Golden Sun needing a Flash 64k. AFAIK there are more games like this, and some others on 512k.  Trying to override this on Retroarch seems to be insufficient, as you need to recompile the core with these new settings for the saves to work again.

**Comment by negativeExponent** [comment]
here an example of the error:

![unknown](https://user-images.githubusercontent.com/54053706/68913149-553ffd80-0795-11ea-9526-342300022bf3.png)
