### ISSUE TITLE
linking takes forever on arm (pi) when using clang

### ISSUE THREAD

**Issue by BlackLotus** [libretro/gpsp#6]
I use clang version 3.5.0 and when compiling gpsp linking doesn't finish (the whole compilation has no problem until libretro_gpsp.so get's build)
This doesn't happen on x86_64.

**Comment by davidgfnet** [comment]
You are probably (not sure!) running out of ram? If it gets to swap then sure it's going to be super slow.
Check out builds in the buildbot (buildbot.libretro.com) or just build it on your PC using a cross compilation toolchain (since it's orders of magnitude faster).
