### ISSUE TITLE
[psp] Going into Quick Menu after running for a while will cause the whole system to freeze.

### ISSUE THREAD

**Issue by hiruko-san** [libretro/gpsp#65]
I was playing Castlevania: Aria of Sorrow. After playing for a while the entire system will freeze and become unresponsive when I go into the Quick Menu in order to Quit game. I've lost progress before I was able to figure this out.

**Comment by davidgfnet** [comment]
Is this still an issue? Since we got rid of libco many old standing issues regarding RA <-> Core messaging and sync have been fixed.

**Comment by hiruko-san** [comment]
I don't currently have my PSP with me so I'm unable to test with a new build of retroarch.

**Comment by bmaupin** [comment]
Does this sound like the same issue?

> While in a core, pressing the menu combo button(s) to return to the menu will often instead cause RetroArch to completely freeze. The screen still shows the core but it will be frozen. The only option is to press the PSP home button and completely exit RetroArch; no other buttons work.

https://github.com/libretro/RetroArch/issues/10247

If that's the case, then it might be an issue with RetroArch itself and not just this core. My guess is some kind of deadlock because it only occurred intermittently and I was never able to reproduce it while I had the debugger running.

**Comment by andymcca** [comment]
I think this was an issue with an older RetroArch build as experienced the same a while back (albeit not on a PSP).  Will try and get confirmation from one of the Discord groups as to whether this still an issue or not.

**Comment by davidgfnet** [comment]
Let's just use the global RA bug. I do not think this is a gpsp specific issue.
I myself never experienced it, but it can indeed be an issue.
