### ISSUE TITLE
[VITA] Games randomly reboot to bios logo 

### ISSUE THREAD

**Issue by spriteice** [libretro/gpsp#69]
I have mainly had this issue with crash bandicoot XS (E) but have also experience it in a few others. It seems to be random, sometimes it will be after 2 min of playing, sometimes 30, sometimes not at all. Maybe there is a setting I am missing or something. 

PSVITA 2000
3.60 henkaku enso 
Official sony card 
Retroarch 1.8.5 (has been happening since big gpsp dynarec update which was around 1.8.2 if I remember correctly)

Other than that it is a great emulator. Keep up the good work 

I did use save states in the games that it happened. Not sure if this could somehow corrupt the actual save and cause issues.

**Comment by herrmartell** [comment]
This happens with Golden Sun The Lost Age as well

**Comment by davidgfnet** [comment]
Since I fixed Golden Sun TLA recently, could you please re-check?

**Comment by Meonk69-Vita** [comment]
Thank you very much for fixed golden sun tla sir! @davidgfnet

**Comment by davidgfnet** [comment]
Okay let's call this fixed. Reopen if it can be reproduced again, but please make sure to use a recent version (that has all the fixes)
Thanks!
