### ISSUE TITLE
Does not save to frontend savefiles only frontend savestates

### ISSUE THREAD

**Issue by unresolvedsymbol** [libretro/gpsp#72]
According to https://docs.libretro.com/library/gpsp/ the emulator should load .sav files but this does not seem to be the case at least for the 3DS port of retroarch

**Comment by herrmartell** [comment]
On VITA, saving state is the only reliable way to save your progress.

**Comment by negativeExponent** [comment]
how so? no file io access on vita?

**Comment by herrmartell** [comment]
There is file access, but the regular saving doesn't work, it gives you an error. Try it with Golden Sun.

**Comment by negativeExponent** [comment]
if Golden Sun is your example, then its not related to file io access but rather a game issue, specifically detection of savefile type and size. i should have fixed this sometime ago 
https://github.com/libretro/gpsp/issues/59
come to think about it, its actually you @herrmartell that created that post.

**Comment by unresolvedsymbol** [comment]
Haven't tried Golden Sun. Only tried Emerald and Super Mario Advanced 2, neither loaded a sav.
