### ISSUE TITLE
Black Wall textures in Golden Sun.

### ISSUE THREAD

**Issue by Jenrais** [libretro/gpsp#74]
Been playing Golden Sun on Retroarch on my vita with the gpSP core and noticed that, when I walked into the walls of certain dungeons (started with Mercury Lighthouse) the walls started to be replaced with these weird black boxed textures that disappeared as soon as I walked away from the walls. This doesn't happen everywhere though so I am not really sure how to fix it. I can sort of ignore them but was wondering if theres something simple that I am missing here. Couldn't really find anything about it anywhere. It is being run on gpSP v0.91. Attached is a save file and savestate of the area in question (Mercury Lighthouse). Running through several areas of the dungeon and hugging the walls makes these weird black boxes appear. Any help?
Edit: Additionally noticed that certain summons simply go into a black screen during combat. I tried the game with the VBA Next core and both the black textures and summon issues are gone, but I have severe audio stuttering and fps drops and am not sure how to fix that.

[save file.zip](https://github.com/libretro/gpsp/files/5169347/save.file.zip)

**Comment by negativeExponent** [comment]
huh can't figure this out.. too many macros :(

OT
im surprised vba next is "slow" on your end. its suppose to have vita threading optimizations. i might take a look at it sometime later, it should be easy to trace since its vba-based

**Comment by davidgfnet** [comment]
I think this is a bug in the arm dynarec, there's a few other games (not too many) that have visual issues. I'm looking into rootcausing this and will send a fix once I do :)

**Comment by Zarke669** [comment]
graphical errors continue :(

**Comment by Richi08** [comment]
I'm getting this issue. Is this still being worked on ?

**Comment by colibris79** [comment]
It's happening to me as well. Does it happen with all the cores or just gpsp?

**Comment by andymcca** [comment]
Checked on this issue using the save file in the OP.  It happens when the bottom of the character sprite meets the wall in front, suggesting some kind of masking issue probably related to sprite obj ordering.  Looking at this issue in general at the moment so will include this game as one to test while trying to fix it.

**Comment by andymcca** [comment]
OK, another update on this having spent some time debugging.

At this point in the game, the OBJ attributes seem to be configured in a way that goes against spec (well spec according to GBATEK anyway).  These attributes should run in priority order, with 0 being highest and 127 being lowest (or rather, joint highest and lowest).  However, at this point in the game, the character sprite is OBJ0 with a priority of 1, whereas OBJ2 and OBJ3 (the black boxes we see drawn) are priority 0!  OBJ2 and OBJ3 are essentially transparent masks to partially cover the up the character sprite as it meets the dungeon wall (feels like some very lazy programming!).

Whilst gpsp seems to take care of the priority order anomaly, the use of transparent OBJ sprites in this way doesn't play nice with the existing code.

In video.c, the macro call constructed for dealing with the tile that produces the black boxes is tile_noflip_4bpp.  Color depth is 4bpp, Combine OP is transparent and Alpha OP is color32.  So far, so good.

Within tile_noflip_4bpp, we assign the current_pixels variable, and this is where things start going wrong!  The way I'm reading the code, current_pixels should be a 32-bit value taken from the tile_ptr address.  So essentially it should be the first 4 bytes of the tile.  For 4bpp tiles, I assume (perhaps wrongly) this will give us an 8 pixel run (seems consistent with the other code and comments)

For the tile in question, all pixel colors are set as zero, so I would expect current_pixels to equal 0x00000000.  But the value that returns in debugging is  0x11111111!  So this will then pass the if evaluation in the next call to tile_4bpp_draw_eight_transparent and merrily draw the tiles as the black pixels we see on screen. 

The code is still wrong, as even if current_pixels returned as 0x00000000, the call to tile_4bpp_draw_eight_transparent would result in nothing being drawn, which would mean the sprite character wouldn't be masked when overlaying the wall background

So 2 things to fix - need to understand if the current_pixels value is being retrieved correctly (I don't think it is), then next need to tackle tile_4bpp_draw_eight_transparent to be implemented correctly (needs to draw the corresponding background pixels, not nothing)

The latter looks quite tricky, especially in situations with multiple BG layers.  

@davidgfnet leaving this explanation here against the issue.  Hopefully you or I, or someone else can take a look at how to fix it in due course.

**Comment by andymcca** [comment]
This issue is on the verge of finally being fixed!  Watch this space 👍

**Comment by davidgfnet** [comment]
Hey there, the new video code fixes the opening (lens flare effect) as well as the black wall issue on some dungeons.
Closing this!

**Comment by Burlz10** [comment]
This doesn’t seem to affect the black screen issue when summoning high level djinn (Neptune and Boreas). Is this being worked on as well?
