### ISSUE TITLE
[3DS]save file is stil ".sav" not ".srm" like other cores

### ISSUE THREAD

**Issue by lencil** [libretro/gpsp#77]
[3DS]save file is stil ".sav" not ".srm" like other cores, like mgba

**Comment by negativeExponent** [comment]
you need to enable libretro save support in core options if you want libretro to handle your save files (for whatever reasons)

relevant commit:
https://github.com/libretro/gpsp/commit/d8225bb313a19bc3b65e257401d3cf5f3eaa32e3

**Comment by lencil** [comment]
ok，seems not in 1.9.0 build. no such options in core settings

**Comment by negativeExponent** [comment]
3ds build has just finished. check if the said option is there. using this new option should fix your other issue:
https://github.com/libretro/gpsp/issues/78
