### ISSUE TITLE
[3DS] load/write saves and save states to content directory failure

### ISSUE THREAD

**Issue by lencil** [libretro/gpsp#78]
1.Settings -> User Interface -> Show Advanced Settings to On
2.Settings -> Saving -> Write Saves to Content Directory to On
3.Settings -> Saving -> Write Save States to Content Directory to On
4.open gpsp core to play any game
5.saves and save states not loaded/saved on content directory.

**Comment by negativeExponent** [comment]
i dont have 3ds, but only reason this fails is if the content directory is not writable. what wrong with using whatever is the defaults on 3ds?
