### ISSUE TITLE
Segfaults with Super Mario Advance 4 - Super Mario Bros. 3 (Europe) (En,Fr,De,Es,It) (Rev 1)

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/gpsp#8]
With Super Mario Advance 4 - Super Mario Bros. 3 (Europe) (En,Fr,De,Es,It) (Rev 1), you can see "Game Boy Player" screen, and then it segfaults.

OS: linux amd64

```
found entry in over ini file.
[New Thread 0x7fffe5f9c700 (LWP 11178)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffeb41c799 in ?? () from /usr/lib/libretro/gpsp_libretro.so
(gdb) bt full
#0  0x00007fffeb41c799 in ?? () from /usr/lib/libretro/gpsp_libretro.so
No symbol table info available.
#1  0x00007fffeb5154d1 in ?? () from /usr/lib/libretro/gpsp_libretro.so
No symbol table info available.
#2  0x00007fffeb515caa in ?? () from /usr/lib/libretro/gpsp_libretro.so
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by sergiobenrocha2** [comment]
I tested with Super Mario Advance 4 - Super Mario Bros. 3 (USA, Australia) (Rev 1), there is no segfault with it.

**Comment by davidgfnet** [comment]
This was indeed a bug in the emulator (interpreter). Thanks for your report, it was very easy to fix and hopefully we've fixed some other bugs for some other games :)
See https://github.com/libretro/gpsp/pull/128 for the fix
