### ISSUE TITLE
Cheat support please.

### ISSUE THREAD

**Issue by 16mpx** [libretro/gpsp#90]
Cheat support for the core please.

**Comment by davidgfnet** [comment]
Just pushed a fix for this, will be out for the next Retroarch release, in a few weeks.

**Comment by 16mpx** [comment]
Tried latest nightly and works perfect with the decrypted codebreaker codes. 

Will the final version be working with the encrypted codes also ?

**Comment by davidgfnet** [comment]
Not planning to. I decrypted all the cheats in the Retroarch repo and most of the cheats available on the internet seem already decrypted. Is there anything in particular that you would like to use?

**Comment by 16mpx** [comment]
Nothing special. My main source for the cheat codes is gamehacking.org and the most gba codebreaker codes are encrypted there. That is why I asked the question. 
I am using CBAcrypt.exe to decrypt the codes at the moment and will check the repo you mentioned also.
